Repository Nexters/PomoNyang-Android, pull requests merged in 2024-09, with the labels that each got.

#108 [CAT-311] USE_FULL_SCREEN_INTENT 제거
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pomonyang/mohanyang/notification/util/NotificationUtils.kt
Labels: feature

#111 chore: 라이브러리 업데이트 및 build-logic 일부 정리
  .github/actions/setup-development-environment/action.yml
  .github/actions/setup-key-environment/action.yml
  build-logic/build.gradle.kts
  build-logic/src/main/java/com/pomonyang/mohanyang/convention/KotlinAndroid.kt
  build-logic/src/main/java/com/pomonyang/mohanyang/convention/ProjectConfigurations.kt
  gradle/libs.versions.toml
Labels: chore

#109 [CAT-313] Timer Service 구현 및 SharedViewModel 관리
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
  app/src/main/java/com/pomonyang/mohanyang/di/.gitkeep
  app/src/main/java/com/pomonyang/mohanyang/di/ServiceModule.kt
  app/src/main/java/com/pomonyang/mohanyang/navigation/MohaNyangNavHost.kt
  app/src/main/java/com/pomonyang/mohanyang/notification/LocalNotificationReceiver.kt
  app/src/main/java/com/pomonyang/mohanyang/ui/ServiceHelper.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/room/dao/PomodoroTimerDao.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/room/enitity/PomodoroTimerEntity.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/room/util/.gitkeep
  data/src/main/java/com/pomonyang/mohanyang/data/local/room/util/TimeUtils.kt
  data/src/main/java/com/pomonyang/mohanyang/data/repository/pomodoro/PomodoroTimerRepository.kt
  data/src/main/java/com/pomonyang/mohanyang/data/repository/pomodoro/PomodoroTimerRepositoryImpl.kt
  data/src/main/java/com/pomonyang/mohanyang/data/repository/util/TimerUtil.kt
  domain/src/main/java/com/pomonyang/mohanyang/domain/usecase/InsertPomodoroInitialDataUseCase.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/di/Qualifier.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/PomodoroConstants.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/home/HomeNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/home/setting/PomodoroSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/home/setting/PomodoroSettingViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/home/time/PomodoroTimeSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/home/time/PomodoroTimeSettingViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/OnboardingNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroTimerViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/focus/PomodoroFocusScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/focus/PomodoroFocusViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/waiting/PomodoroRestWaitingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/waiting/PomodoroRestWaitingViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/util/PomodoroTimerService.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/util/PomodoroTimerServiceExtras.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/util/TimerUtils.kt
Labels: bug

#110 HttpRequest-UserAgent 구현
  data/src/main/java/com/pomonyang/mohanyang/data/remote/di/NetworkModule.kt
  data/src/main/java/com/pomonyang/mohanyang/data/remote/interceptor/HttpRequestInterceptor.kt
Labels: chore

#32 [CAT-101] Firebase Distribution 자동화
  .github/workflows/deploy_firebase-distribution_debug.yml
  .github/workflows/deploy_firebase-distribution_release.yml
Labels: chore

#116 [Feature] Release 시 앱 버전 자동 업데이트
  .github/PULL_REQUEST_TEMPLATE/BASIC_PR_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/RELEASE_PR_TEMPLATE.md
  .github/actions/get-app-version/action.yml
  .github/actions/update-app-version/action.yml
  .github/workflows/deploy-new-version.yml
  app-version.json
  app/build.gradle.kts
  build-logic/build.gradle.kts
  build-logic/src/main/java/com/pomonyang/mohanyang/AppVersionPlugin.kt
Labels: feature

#113 [Feature] Datadog Setup
  app/build.gradle.kts
  app/src/main/java/com/pomonyang/mohanyang/MohaNyangApplication.kt
  build-logic/build.gradle.kts
  build-logic/src/main/java/com/pomonyang/mohanyang/AndroidDatadogConventionPlugin.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: feature

#122 test
  .github/PULL_REQUEST_TEMPLATE/BASIC_PR_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/RELEASE_PR_TEMPLATE.md
  .github/actions/get-app-version/action.yml
  .github/actions/setup-key-environment/action.yml
  .github/actions/update-app-version/action.yml
  .github/workflows/deploy_google_play_store.yml
  app-version.json
  app/build.gradle.kts
  build-logic/build.gradle.kts
  build-logic/src/main/java/com/pomonyang/mohanyang/AppVersionPlugin.kt
Labels: chore

#121 [Feature] Release시 App Version 자동 업데이트 기능 구현
  .github/PULL_REQUEST_TEMPLATE/BASIC_PR_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/RELEASE_PR_TEMPLATE.md
  .github/actions/get-app-version/action.yml
  .github/actions/update-app-version/action.yml
  .github/workflows/deploy-new-version.yml
  app-version.json
  app/build.gradle.kts
  build-logic/build.gradle.kts
  build-logic/src/main/java/com/pomonyang/mohanyang/AppVersionPlugin.kt
Labels: feature
