Repository Nexters/PomoNyang-Android, pull requests merged in 2024-07, with the labels that each got.

#3 [Feature/cat 11] Google Secretes API 추가
  .gitignore
  app/build.gradle.kts
  build-logic/build.gradle.kts
  build-logic/src/main/java/com/pomonyang/AndroidApplicationConventionPlugin.kt
  build-logic/src/main/java/com/pomonyang/AndroidLibraryConventionPlugin.kt
  build-logic/src/main/java/com/pomonyang/convention/KotlinAndroid.kt
  build-logic/src/main/java/com/pomonyang/convention/Secrets.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: chore

#4 [CAT-18] Timber Tree 추가 / PR Template 일부 수정
  .github/PULL_REQUEST_TEMPLATE.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pomonyang/MainActivity.kt
  app/src/main/java/com/pomonyang/PomoNyangApplication.kt
  app/src/main/java/com/pomonyang/ui/TimberInitializer.kt
Labels: chore

#5 [CAT-19] Firebase 연동 및 추가
  .gitignore
  app/build.gradle.kts
  build-logic/build.gradle.kts
  build-logic/src/main/java/com/pomonyang/AndroidApplicationFirebaseConvention.kt
  build-logic/src/main/java/com/pomonyang/convention/GithubUtils.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: chore

#7 [CAT-33] module gradle 정리 및 의존성 추가
  app/build.gradle.kts
  app/src/main/java/com/pomonyang/MainActivity.kt
  app/src/main/java/com/pomonyang/ui/theme/Theme.kt
  data/build.gradle.kts
  domain/build.gradle.kts
  gradle/libs.versions.toml
  presentation/build.gradle.kts
Labels: chore

#8 [CAT-34] 각 모듈 패키징 구조 추가
  app/src/main/java/com/pomonyang/di/.gitkeep
  app/src/main/java/com/pomonyang/navigation/.gitkeep
  app/src/main/java/com/pomonyang/util/.gitkeep
  data/src/main/java/com/pomonyang/data/local/datastore/di/.gitkeep
  data/src/main/java/com/pomonyang/data/local/datastore/model/.gitkeep
  data/src/main/java/com/pomonyang/data/local/datastore/util/.gitkeep
  data/src/main/java/com/pomonyang/data/local/room/dao/.gitkeep
  data/src/main/java/com/pomonyang/data/local/room/di/.gitkeep
  data/src/main/java/com/pomonyang/data/local/room/util/.gitkeep
  data/src/main/java/com/pomonyang/data/remote/di/.gitkeep
  data/src/main/java/com/pomonyang/data/remote/model/.gitkeep
  data/src/main/java/com/pomonyang/data/remote/repository/impl/.gitkeep
  data/src/main/java/com/pomonyang/data/remote/util/.gitkeep
  presentation/src/main/java/com/pomonyang/presentation/designsystem/.gitkeep
  presentation/src/main/java/com/pomonyang/presentation/screen/.gitkeep
  presentation/src/main/java/com/pomonyang/presentation/util/.gitkeep
Labels: chore

#10 [CAT-37] Ktlint pre-commit 추가
  .editorconfig
  app/build.gradle.kts
  app/src/main/java/com/pomonyang/MainActivity.kt
  app/src/main/java/com/pomonyang/PomoNyangApplication.kt
  app/src/main/java/com/pomonyang/ui/DebugTimberTree.kt
  app/src/main/java/com/pomonyang/ui/theme/Color.kt
  app/src/main/java/com/pomonyang/ui/theme/Theme.kt
  app/src/main/java/com/pomonyang/ui/theme/Type.kt
  build-logic/settings.gradle.kts
  build-logic/src/main/java/com/pomonyang/AndroidApplicationConventionPlugin.kt
  build-logic/src/main/java/com/pomonyang/AndroidApplicationFirebaseConventionPlugin.kt
  build-logic/src/main/java/com/pomonyang/AndroidLibraryConventionPlugin.kt
  build-logic/src/main/java/com/pomonyang/convention/AndroidCompose.kt
  build-logic/src/main/java/com/pomonyang/convention/DependencyHandlerExtensions.kt
  build-logic/src/main/java/com/pomonyang/convention/GithubUtils.kt
  build-logic/src/main/java/com/pomonyang/convention/KotlinAndroid.kt
  build-logic/src/main/java/com/pomonyang/convention/ProjectExtensions.kt
  build.gradle.kts
  data/build.gradle.kts
  domain/build.gradle.kts
  gradle/libs.versions.toml
  presentation/build.gradle.kts
Labels: chore

#11 [CAT-36] remote 영역 di 및 기본 세팅
  data/src/main/java/com/pomonyang/data/remote/datasource/.gitkeep
  data/src/main/java/com/pomonyang/data/remote/di/NetworkModule.kt
  data/src/main/java/com/pomonyang/data/remote/interceptor/HttpRequestInterceptor.kt
  data/src/main/java/com/pomonyang/data/remote/service/PomoNyangService.kt
  data/src/main/java/com/pomonyang/data/remote/util/.gitkeep
  data/src/main/java/com/pomonyang/data/remote/util/NetworkResultCall.kt
  data/src/main/java/com/pomonyang/data/remote/util/NetworkResultCallAdapter.kt
  data/src/main/java/com/pomonyang/data/remote/util/NetworkResultCallAdapterFactory.kt
Labels: feature

#13 debug app name 변경
  app/src/debug/res/values/strings.xml
Labels: chore

#12 [CAT-38] data 레이어 local 세팅 및 di
  data/build.gradle.kts
  data/src/main/java/com/pomonyang/data/local/datastore/di/.gitkeep
  data/src/main/java/com/pomonyang/data/local/datastore/di/DataStoreModule.kt
  data/src/main/java/com/pomonyang/data/local/room/dao/.gitkeep
  data/src/main/java/com/pomonyang/data/local/room/dao/SampleDao.kt
  data/src/main/java/com/pomonyang/data/local/room/database/SampleDataBase.kt
  data/src/main/java/com/pomonyang/data/local/room/di/.gitkeep
  data/src/main/java/com/pomonyang/data/local/room/di/RoomModule.kt
  data/src/main/java/com/pomonyang/data/local/room/enitity/SampleEntity.kt
  gradle/libs.versions.toml
Labels: feature

#14 [CAT-37] lint 의존성 제거
  build-logic/src/main/java/com/pomonyang/AndroidApplicationConventionPlugin.kt
  build-logic/src/main/java/com/pomonyang/AndroidLibraryConventionPlugin.kt
  build.gradle.kts
  domain/build.gradle.kts
  gradle/libs.versions.toml
Labels: chore

#15 [CAT-32] 네트워크 상태를 갖고 있는 NetworkConnectivityManager 구현
  .editorconfig
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pomonyang/MainActivity.kt
  app/src/main/java/com/pomonyang/ui/theme/Type.kt
  data/src/main/java/com/pomonyang/data/remote/di/NetworkModule.kt
  data/src/main/java/com/pomonyang/data/remote/util/NetworkConnectivityManager.kt
Labels: feature

#16 [CAT-50] Modifier 의 클릭 관련 확장함수 / Preview 추가
  app/src/main/java/com/pomonyang/MainActivity.kt
  presentation/src/main/java/com/pomonyang/presentation/util/.gitkeep
  presentation/src/main/java/com/pomonyang/presentation/util/ModifierUtils.kt
  presentation/src/main/java/com/pomonyang/presentation/util/PreviewUtils.kt
Labels: chore

#23 [CAT-46] MVI BaseViewModel 구현
  presentation/src/main/java/com/pomonyang/presentation/base/BaseViewElements.kt
  presentation/src/main/java/com/pomonyang/presentation/base/BaseViewModel.kt
Labels: feature

#26 [CAT-63] Github Auto Assign & Reviewer
  .github/auto_assign_config.yml
  .github/workflows/pr_auto_assign.yml
  data/src/main/java/com/pomonyang/data/local/datastore/di/DataStoreModule.kt
Labels: chore

#27 [CAR-67] Network Monitor 코드 일부 수정 및 리팩
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pomonyang/MainActivity.kt
  data/src/main/AndroidManifest.xml
  data/src/main/java/com/pomonyang/data/remote/di/NetworkModule.kt
  data/src/main/java/com/pomonyang/data/remote/util/NetworkConnectivityManager.kt
  data/src/main/java/com/pomonyang/data/remote/util/NetworkMonitor.kt
Labels: refactor

#28 [CAT-64] Home, Onboarding Screen Navigation / PomoNyangNavHost 구현
  app/src/main/java/com/pomonyang/MainActivity.kt
  app/src/main/java/com/pomonyang/navigation/.gitkeep
  app/src/main/java/com/pomonyang/navigation/PomoNyangNavHost.kt
  app/src/main/java/com/pomonyang/ui/PomoNyangApp.kt
  app/src/main/java/com/pomonyang/ui/PomoNyangAppState.kt
  presentation/src/main/java/com/pomonyang/presentation/screen/.gitkeep
  presentation/src/main/java/com/pomonyang/presentation/screen/home/HomeNavigator.kt
  presentation/src/main/java/com/pomonyang/presentation/screen/home/HomeScreen.kt
  presentation/src/main/java/com/pomonyang/presentation/screen/onboarding/OnboardingNavigator.kt
  presentation/src/main/java/com/pomonyang/presentation/screen/onboarding/OnboardingScreen.kt
Labels: feature

#29 [CAT-69] 디바이스 및 유저 인증 모듈 구현
  .editorconfig
  data/src/main/java/com/pomonyang/data/local/datastore/datasource/deviceid/DeviceIdLocalDataSource.kt
  data/src/main/java/com/pomonyang/data/local/datastore/datasource/deviceid/DeviceIdLocalDataSourceImpl.kt
  data/src/main/java/com/pomonyang/data/local/datastore/datasource/token/TokenLocalDataSource.kt
  data/src/main/java/com/pomonyang/data/local/datastore/datasource/token/TokenLocalDataSourceImpl.kt
  data/src/main/java/com/pomonyang/data/local/datastore/di/DataStoreModule.kt
  data/src/main/java/com/pomonyang/data/local/datastore/di/DataStoreQualifier.kt
  data/src/main/java/com/pomonyang/data/local/datastore/di/LocalDataSourceModule.kt
  data/src/main/java/com/pomonyang/data/remote/datasource/auth/AuthRemoteDataSource.kt
  data/src/main/java/com/pomonyang/data/remote/datasource/auth/AuthRemoteDataSourceImpl.kt
  data/src/main/java/com/pomonyang/data/remote/di/ClientQualifier.kt
  data/src/main/java/com/pomonyang/data/remote/di/NetworkModule.kt
  data/src/main/java/com/pomonyang/data/remote/di/RemoteDataSourceModule.kt
  data/src/main/java/com/pomonyang/data/remote/interceptor/HttpRequestInterceptor.kt
  data/src/main/java/com/pomonyang/data/remote/interceptor/TokenRefreshInterceptor.kt
  data/src/main/java/com/pomonyang/data/remote/model/request/RefreshTokenRequest.kt
  data/src/main/java/com/pomonyang/data/remote/model/response/TokenResponse.kt
  data/src/main/java/com/pomonyang/data/remote/service/AuthService.kt
Labels: feature

#34 [CAT-113] theme 모듈 이동
  app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
  app/src/main/java/com/pomonyang/mohanyang/MohaNyangApplication.kt
  app/src/main/java/com/pomonyang/mohanyang/util/.gitkeep
  app/src/main/java/com/pomonyang/mohanyang/util/DebugTimberTree.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/theme/Color.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/theme/Theme.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/theme/Type.kt
Labels: refactor

#36 [CAT-105] colorScheme 추가
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/theme/Color.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/theme/Theme.kt
Labels: style
