Repository Nexters/PomoNyang-Android, pull requests merged in 2024-08, with the labels that each got.

#37 [CAT-114] 잠금 상태 모니터 구현
  data/src/main/AndroidManifest.xml
  data/src/main/java/com/pomonyang/mohanyang/data/local/device/receiver/LockScreenBroadcastReceiver.kt
Labels: feature

#35 [CAT-103] Typography setup
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/theme/Theme.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/theme/Type.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/util/DpPxSpConversionUtils.kt
  presentation/src/main/res/font/pretendard_bold.ttf
  presentation/src/main/res/font/pretendard_regular.ttf
  presentation/src/main/res/font/pretendard_semibold.ttf
Labels: style

#40 [CAT-134] 디자인 시스템 아이콘
  app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/icon/MnLargeIcon.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/icon/MnMediumIcon.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/icon/MnSmallIcon.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/icon/MnXLargeIcon.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/icon/MnXSmallIcon.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/token/IconSize.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/theme/Color.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/theme/Theme.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/theme/Type.kt
  presentation/src/main/res/drawable/ic_null.xml
Labels: feature

#39 [CAT-138] radius / storke / token 추가
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/.gitkeep
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/icon/MnLargeIcon.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/icon/MnMediumIcon.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/icon/MnSmallIcon.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/icon/MnXLargeIcon.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/icon/MnXSmallIcon.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/token/MnColor.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/token/MnIconSize.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/token/MnRadius.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/token/MnSpacing.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/token/MnStroke.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/token/MnTypography.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/theme/MnTheme.kt
Labels: style

#42 [CAT-140] MnTopAppBar 구현 / Icon LocalContentColor로 수정
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/icon/MnLargeIcon.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/icon/MnMediumIcon.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/icon/MnSmallIcon.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/icon/MnXLargeIcon.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/icon/MnXSmallIcon.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/token/MnColor.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/topappbar/MnTopAppBar.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/topappbar/MnTopAppBarDefaults.kt
Labels: feature

#41 [CAT-122] MnTooltip 구현
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/tooltip/MnTooltip.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/tooltip/MnTooltipDefaults.kt
  presentation/src/main/res/values/strings.xml
Labels: feature

#43 [CAT-144] MnDialog 구현
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/dialog/MnDialog.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/dialog/MnDialogDefaults.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/OnboardingScreen.kt
Labels: feature

#46 [CAT-145] MnToastSnackbar 컴포넌트 구현
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/toast/MnToastSnackbarHost.kt
Labels: feature

#45 [CAT-139] MnButton 컴포넌트 구현
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/button/box/MnBoxButton.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/button/box/MnBoxButtonColorType.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/button/box/MnBoxButtonColors.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/button/box/MnBoxButtonStyles.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/button/common/MnButtonStyleProperties.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/button/common/MnPressableWrapper.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/button/icon/MnIconButton.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/button/round/MnRoundButton.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/button/round/MnRoundButtonColorType.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/button/round/MnRoundButtonColors.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/button/select/MnSelectButton.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/button/select/MnSelectButtonSelector.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/button/text/MnTextButton.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/button/text/MnTextButtonStyles.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/button/toggle/MnToggleButton.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/button/toggle/MnToggleButtonSize.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/token/MnInteraction.kt
Labels: feature

#47 [CAT-163] 유저 토큰 발급 및 저장 로직 구현
  app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/datastore/datasource/deviceid/DeviceIdLocalDataSourceImpl.kt
  data/src/main/java/com/pomonyang/mohanyang/data/remote/model/request/TokenRequest.kt
  data/src/main/java/com/pomonyang/mohanyang/data/remote/model/response/TokenResponse.kt
  data/src/main/java/com/pomonyang/mohanyang/data/remote/repository/impl/.gitkeep
  data/src/main/java/com/pomonyang/mohanyang/data/remote/service/AuthService.kt
  data/src/main/java/com/pomonyang/mohanyang/data/repository/di/RepositoryModule.kt
  data/src/main/java/com/pomonyang/mohanyang/data/repository/user/UserRepository.kt
  data/src/main/java/com/pomonyang/mohanyang/data/repository/user/UserRepositoryImpl.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/OnboardingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/OnboardingViewModel.kt
Labels: feature

#48 [CAT-166] MnBottomSheet / MnSelectList
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/bottomsheet/MnBottomSheet.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/bottomsheet/MnBottomSheetDefaults.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/button/box/MnBoxButton.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/button/icon/MnIconButton.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/button/round/MnRoundButton.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/button/select/MnSelectButton.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/button/select/MnSelectList.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/button/text/MnTextButton.kt
Labels: feature

#49 [CAT-169] 온보딩 가이드 화면 UI 구현
  app/src/main/java/com/pomonyang/mohanyang/navigation/MohaNyangNavHost.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/OnboardingNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/OnboardingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/guide/OnboardingGuideScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/guide/OnboardingGuideViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/model/OnboardingGuideContent.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/naming/OnboardingNamingCatScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: feature

#51 [CAT-164] 카테고리 관련 비즈니스 로직 / BottomSheet 연결 / Snackbar
  app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
  app/src/main/java/com/pomonyang/mohanyang/navigation/MohaNyangNavHost.kt
  app/src/main/java/com/pomonyang/mohanyang/ui/MohaNyangApp.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/datastore/datasource/pomodoro/PomodoroLocalDataSource.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/datastore/datasource/pomodoro/PomodoroLocalDataSourceImpl.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/datastore/di/DataStoreModule.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/datastore/di/DataStoreQualifier.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/datastore/di/LocalDataSourceModule.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/room/dao/PomodoroSettingDao.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/room/dao/SampleDao.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/room/database/PomodoroSettingDataBase.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/room/database/SampleDataBase.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/room/di/RoomModule.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/room/enitity/PomodoroSettingEntity.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/room/enitity/SampleEntity.kt
  data/src/main/java/com/pomonyang/mohanyang/data/remote/datasource/pomodoro/PomodoroSettingRemoteDataSource.kt
  data/src/main/java/com/pomonyang/mohanyang/data/remote/datasource/pomodoro/PomodoroSettingRemoteDataSourceImpl.kt
  data/src/main/java/com/pomonyang/mohanyang/data/remote/di/NetworkModule.kt
  data/src/main/java/com/pomonyang/mohanyang/data/remote/di/RemoteDataSourceModule.kt
  data/src/main/java/com/pomonyang/mohanyang/data/remote/model/request/UpdateCategoryInfoRequest.kt
  data/src/main/java/com/pomonyang/mohanyang/data/remote/model/response/PomodoroSettingResponse.kt
  data/src/main/java/com/pomonyang/mohanyang/data/remote/service/MohaNyangService.kt
  data/src/main/java/com/pomonyang/mohanyang/data/repository/di/RepositoryModule.kt
  data/src/main/java/com/pomonyang/mohanyang/data/repository/pomodoro/PomodoroSettingRepository.kt
  data/src/main/java/com/pomonyang/mohanyang/data/repository/pomodoro/PomodoroSettingRepositoryImpl.kt
  domain/build.gradle.kts
  domain/src/main/java/com/pomonyang/mohanyang/domain/.gitkeep
  domain/src/main/java/com/pomonyang/mohanyang/domain/model/PomodoroCategoryModel.kt
  domain/src/main/java/com/pomonyang/mohanyang/domain/usecase/GetPomodoroSettingListUseCase.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/toast/MnToastSnackbarHost.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/util/FlowUtils.kt
  presentation/src/main/res/values/strings.xml
Labels: feature

#52 [CAT-181] 집중 / 휴식시간 변경에 사용되는 Time Picker 구현
  gradle/libs.versions.toml
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/picker/MnWheelMinutePicker.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/picker/MnWheelPickerDefaults.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/token/MnTypography.kt
Labels: feature

#50 [CAT-170] 고양이 이름 짓기 화면 UI
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/textfield/MnTextField.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/OnboardingNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/naming/CatNameVerifier.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/naming/OnboardingNamingCatScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/naming/OnboardingNamingCatViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: feature

#53 [CAT-165] 시간 변경 Screen 구현
  app/src/main/java/com/pomonyang/mohanyang/navigation/MohaNyangNavHost.kt
  app/src/main/java/com/pomonyang/mohanyang/ui/MohaNyangApp.kt
  app/src/main/java/com/pomonyang/mohanyang/ui/MohaNyangAppState.kt
  data/src/main/java/com/pomonyang/mohanyang/data/repository/pomodoro/PomodoroSettingRepository.kt
  data/src/main/java/com/pomonyang/mohanyang/data/repository/pomodoro/PomodoroSettingRepositoryImpl.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/picker/MnWheelMinutePicker.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/picker/MnWheelPickerDefaults.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/home/HomeNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/time/PomodoroTimeSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/time/PomodoroTimeSettingViewModel.kt
Labels: feature

#56 [CAT-196] Splash Screen API 적용 및 토큰 갱신 로직 이전
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
  app/src/main/res/values/themes.xml
  domain/src/main/java/com/pomonyang/mohanyang/domain/usecase/GetTokenByDeviceIdUseCase.kt
  gradle/libs.versions.toml
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/OnboardingViewModel.kt
Labels: feature

#58 [CAT-218] popupPositionProvider를 사용하는 tooltip 추가
  app/src/main/AndroidManifest.xml
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/tooltip/MnTooltip.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/OnboardingNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/naming/OnboardingNamingCatScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingScreen.kt
Labels: bug

#59 [CAT-200] 뽀모도르 타이머 화면 구현
  app/src/main/java/com/pomonyang/mohanyang/navigation/MohaNyangNavHost.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/picker/MnWheelMinutePicker.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/home/HomeNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/home/HomeScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/OnboardingNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroTimerScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/component/CategoryBox.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/time/PomodoroTimeSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/util/PreviewUtils.kt
  presentation/src/main/res/values/strings.xml
Labels: feature

#57 [CAT-135] 로컬 집중 알림 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
  app/src/main/java/com/pomonyang/mohanyang/di/ManagerModule.kt
  app/src/main/java/com/pomonyang/mohanyang/notification/FocusNotificationService.kt
  app/src/main/java/com/pomonyang/mohanyang/notification/LocalNotificationReceiver.kt
  app/src/main/java/com/pomonyang/mohanyang/notification/MnAlarmManager.kt
  app/src/main/java/com/pomonyang/mohanyang/notification/util/NotificationUtils.kt
  app/src/main/res/values/strings.xml
  data/src/main/java/com/pomonyang/mohanyang/data/local/device/util/LockScreenUtils.kt
Labels: feature

#61 [CAT-222] Response 객체들 기본값 추가
  data/src/main/java/com/pomonyang/mohanyang/data/remote/model/response/CatTypeResponse.kt
  data/src/main/java/com/pomonyang/mohanyang/data/remote/model/response/PomodoroSettingResponse.kt
  data/src/main/java/com/pomonyang/mohanyang/data/remote/model/response/UserInfoResponse.kt
Labels: bug

#60 [CAT-203] FCM 세팅 및 MnFirebaseMessagingService 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
  app/src/main/java/com/pomonyang/mohanyang/notification/MnFirebaseMessagingService.kt
  app/src/main/java/com/pomonyang/mohanyang/notification/util/NotificationUtils.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/datastore/datasource/token/TokenLocalDataSource.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/datastore/datasource/token/TokenLocalDataSourceImpl.kt
  data/src/main/java/com/pomonyang/mohanyang/data/remote/model/request/RegisterPushTokenRequest.kt
  data/src/main/java/com/pomonyang/mohanyang/data/remote/service/MohaNyangService.kt
  data/src/main/java/com/pomonyang/mohanyang/data/repository/di/RepositoryModule.kt
  data/src/main/java/com/pomonyang/mohanyang/data/repository/push/PushAlarmRepository.kt
  data/src/main/java/com/pomonyang/mohanyang/data/repository/push/PushAlarmRepositoryImpl.kt
  gradle/libs.versions.toml
Labels: feature

#62 [CAT-225] 뽀모도르 세팅과 관련된 데이터 리팩 / String Format 값에 맞게 수정
  domain/src/main/java/com/pomonyang/mohanyang/domain/model/setting/PomodoroCategoryModel.kt
  domain/src/main/java/com/pomonyang/mohanyang/domain/usecase/GetSelectedPomodoroSettingUseCase.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/picker/MnWheelMinutePicker.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/naming/OnboardingNamingCatViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroTimerScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroTimerViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/time/PomodoroTimeSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/time/PomodoroTimeSettingViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: refactor

#63 [CAT-219] 뽀모도르 비즈니스 로직 분리 및 공통 컴포넌트 분리
  app/src/main/java/com/pomonyang/mohanyang/navigation/MohaNyangNavHost.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/component/CatRive.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/component/CategoryBox.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/component/Timer.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/tooltip/MnTooltip.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/OnboardingNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/guide/OnboardingGuideScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/naming/OnboardingNamingCatScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroTimerScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroTimerViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestRoute.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/time/PomodoroTimeSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/util/TimeUtils.kt
  presentation/src/main/res/values/strings.xml
Labels: feature

#66 [CAT-233] 뽀모도르 카테고리 아이콘 매치
  data/src/main/java/com/pomonyang/mohanyang/data/local/room/enitity/PomodoroSettingEntity.kt
  domain/src/main/java/com/pomonyang/mohanyang/domain/usecase/GetPomodoroSettingListUseCase.kt
  domain/src/main/java/com/pomonyang/mohanyang/domain/usecase/GetSelectedPomodoroSettingUseCase.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/model/setting/PomodoroCategoryModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/model/setting/PomodoroCategoryType.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroTimerScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroTimerViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/time/PomodoroTimeSettingViewModel.kt
Labels: feature

#65 [CAT-228] 온보딩 화면 해상도 대응
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/guide/OnboardingGuideScreen.kt
Labels: feature

#64 [CAT-226] 휴식 대기 화면 및 로직 구현
  data/src/main/java/com/pomonyang/mohanyang/data/local/room/dao/PomodoroSettingDao.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/room/enitity/PomodoroSettingEntity.kt
  data/src/main/java/com/pomonyang/mohanyang/data/remote/service/MohaNyangService.kt
  data/src/main/java/com/pomonyang/mohanyang/data/repository/pomodoro/PomodoroSettingRepository.kt
  data/src/main/java/com/pomonyang/mohanyang/data/repository/pomodoro/PomodoroSettingRepositoryImpl.kt
  domain/src/main/java/com/pomonyang/mohanyang/domain/usecase/AdjustPomodoroTimeUseCase.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/component/Timer.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/picker/MnWheelMinutePicker.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/PomodoroConstants.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroTimerScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroTimerViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestRoute.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestWaitingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestWaitingViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/time/PomodoroTimeSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/time/PomodoroTimeSettingViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: feature

#68 [CAT-234] 오프라인 알림 팝업 구현
  app/src/main/java/com/pomonyang/mohanyang/ui/MohaNyangApp.kt
  app/src/main/res/values/strings.xml
Labels: feature

#67 [CAT-227] 토큰 갱신 로직 오류 수정
  data/src/main/java/com/pomonyang/mohanyang/data/remote/datasource/auth/AuthRemoteDataSource.kt
  data/src/main/java/com/pomonyang/mohanyang/data/remote/datasource/auth/AuthRemoteDataSourceImpl.kt
  data/src/main/java/com/pomonyang/mohanyang/data/remote/di/NetworkModule.kt
  data/src/main/java/com/pomonyang/mohanyang/data/remote/interceptor/HttpRequestInterceptor.kt
  data/src/main/java/com/pomonyang/mohanyang/data/remote/interceptor/TokenRefreshInterceptor.kt
Labels: bug

#70 [CAT-229] 아이콘 리소스 추가
  app/src/main/java/com/pomonyang/mohanyang/notification/FocusNotificationService.kt
  domain/src/main/java/com/pomonyang/mohanyang/domain/model/cat/CatType.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/component/CategoryBox.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/component/TimerType.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/button/select/MnSelectList.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/picker/MnWheelMinutePicker.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/textfield/MnTextField.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/model/cat/CatInfoModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/model/cat/CatType.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/model/setting/PomodoroCategoryType.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/model/user/UserInfoModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/naming/OnboardingNamingCatScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroTimerScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestWaitingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/time/PomodoroTimeSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/time/PomodoroTimeSettingViewModel.kt
  presentation/src/main/res/drawable/ic_alert.xml
  presentation/src/main/res/drawable/ic_arrow_down.xml
  presentation/src/main/res/drawable/ic_arrow_left.xml
  presentation/src/main/res/drawable/ic_arrow_right.xml
  presentation/src/main/res/drawable/ic_arrow_up.xml
  presentation/src/main/res/drawable/ic_book.xml
  presentation/src/main/res/drawable/ic_category_default.xml
  presentation/src/main/res/drawable/ic_check.xml
  presentation/src/main/res/drawable/ic_chevron_down.xml
  presentation/src/main/res/drawable/ic_chevron_left.xml
  presentation/src/main/res/drawable/ic_chevron_right.xml
  presentation/src/main/res/drawable/ic_chevron_up.xml
  presentation/src/main/res/drawable/ic_clock.xml
  presentation/src/main/res/drawable/ic_close.xml
  presentation/src/main/res/drawable/ic_feedback.xml
  presentation/src/main/res/drawable/ic_focus.xml
  presentation/src/main/res/drawable/ic_heart.xml
  presentation/src/main/res/drawable/ic_memo.xml
  presentation/src/main/res/drawable/ic_menu.xml
  presentation/src/main/res/drawable/ic_minus.xml
  presentation/src/main/res/drawable/ic_monitor.xml
  presentation/src/main/res/drawable/ic_pen.xml
  presentation/src/main/res/drawable/ic_play.xml
  presentation/src/main/res/drawable/ic_plus.xml
  presentation/src/main/res/drawable/ic_rest.xml
  presentation/src/main/res/drawable/ic_star.xml
  presentation/src/main/res/drawable/ic_user.xml
  presentation/src/main/res/values/strings.xml
Labels: feature

#71 [CAT-241] 뽀모도르 세팅 온보딩 툴팁 State 수정
  app/src/main/java/com/pomonyang/mohanyang/navigation/MohaNyangNavHost.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/OnboardingNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingViewModel.kt
Labels: bug

#72 [CAT-242] CatRive의 툴팁 Pop 대신 Component 조합으로 수정
  app/src/main/java/com/pomonyang/mohanyang/navigation/MohaNyangNavHost.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/component/CatRive.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/tooltip/MnTooltip.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/model/cat/CatType.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/OnboardingNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/naming/OnboardingNamingCatScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroTimerScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: refactor

#73 [CAT-243] Snackbar 아이콘 추가 작업
  app/src/main/java/com/pomonyang/mohanyang/navigation/MohaNyangNavHost.kt
  app/src/main/java/com/pomonyang/mohanyang/ui/MohaNyangApp.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/toast/MnToastSnackbarHost.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestWaitingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestWaitingViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/time/PomodoroTimeSettingScreen.kt
Labels: feature

#75 [CAT-244] 낮은 OS 툴팁 및 휠피커 대응
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/picker/MnWheelMinutePicker.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/picker/MnWheelPickerDefaults.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingScreen.kt
Labels: bug

#76 [CAT-237] MnNotificationManager 구현
  app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
  app/src/main/java/com/pomonyang/mohanyang/notification/LocalNotificationReceiver.kt
  app/src/main/java/com/pomonyang/mohanyang/notification/MnAlarmManager.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/util/MnNotificationManager.kt
Labels: feature

#79 [CAT-248] NotificationLocalDataStore 구현
  data/src/main/java/com/pomonyang/mohanyang/data/local/datastore/datasource/notification/NotificationLocalDataSource.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/datastore/datasource/notification/NotificationLocalDataSourceImpl.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/datastore/di/DataStoreModule.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/datastore/di/DataStoreQualifier.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/datastore/di/LocalDataSourceModule.kt
  data/src/main/java/com/pomonyang/mohanyang/data/repository/push/PushAlarmRepository.kt
  data/src/main/java/com/pomonyang/mohanyang/data/repository/push/PushAlarmRepositoryImpl.kt
Labels: feature

#78 [CAT-247] 포커스, 휴식 알림 / 시간 조정 rebase 잘못됐던 것들 수정
  app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
  app/src/main/java/com/pomonyang/mohanyang/notification/FocusNotificationService.kt
  app/src/main/java/com/pomonyang/mohanyang/notification/LocalNotificationReceiver.kt
  data/src/main/java/com/pomonyang/mohanyang/data/remote/model/response/UserInfoResponse.kt
  domain/src/main/java/com/pomonyang/mohanyang/domain/usecase/AdjustPomodoroTimeUseCase.kt
  domain/src/main/java/com/pomonyang/mohanyang/domain/usecase/GetSelectedPomodoroSettingUseCase.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/component/FocusTimerSelecterButtons.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/button/select/MnSelectButton.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/picker/MnWheelMinutePicker.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/PomodoroConstants.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroTimerScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroTimerViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestWaitingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestWaitingViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/time/PomodoroTimeSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/util/MnNotificationManager.kt
Labels: feature

#80 [CAT-250] 뽀모도르 데이터 Local/Remote 연동
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/room/dao/PomodoroTimerDao.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/room/database/PomodoroTimerDataBase.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/room/di/RoomModule.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/room/enitity/PomodoroTimerEntity.kt
  data/src/main/java/com/pomonyang/mohanyang/data/remote/datasource/.gitkeep
  data/src/main/java/com/pomonyang/mohanyang/data/remote/model/request/PomodoroTimerRequest.kt
  data/src/main/java/com/pomonyang/mohanyang/data/remote/service/MohaNyangService.kt
  data/src/main/java/com/pomonyang/mohanyang/data/repository/di/RepositoryModule.kt
  data/src/main/java/com/pomonyang/mohanyang/data/repository/pomodoro/PomodoroTimerRepository.kt
  data/src/main/java/com/pomonyang/mohanyang/data/repository/pomodoro/PomodoroTimerRepositoryImpl.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroTimerScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroTimerViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestWaitingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestWaitingViewModel.kt
Labels: feature

#81 [CAT-220] 마이페이지 구현 및 Push Validation 추가 + 스크린 nav animation 수정
  app/src/main/java/com/pomonyang/mohanyang/navigation/MohaNyangNavHost.kt
  app/src/main/java/com/pomonyang/mohanyang/notification/LocalNotificationReceiver.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/component/CatRive.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/MyPageNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/MyPageScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/MyPageViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/component/FocusStatisticBox.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/profile/CatProfileScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/naming/CatNameVerifier.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/time/PomodoroTimeSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/util/MnNotificationManager.kt
  presentation/src/main/res/values/strings.xml
Labels: feature

#82 [CAT-253] RIVE 적용
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/component/CatRive.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/picker/MnWheelMinutePicker.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/model/cat/CatType.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/MyPageScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/profile/CatProfileScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/OnboardingNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/guide/OnboardingGuideScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/naming/OnboardingNamingCatScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroTimerScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestWaitingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/time/PomodoroTimeSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/util/ModifierUtils.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/util/TimeUtils.kt
  presentation/src/main/res/drawable/ic_check_32.xml
  presentation/src/main/res/drawable/ic_play_32.xml
  presentation/src/main/res/raw/cat_motion_transparent.riv
  presentation/src/main/res/raw/cat_select_motion.riv
Labels: feature

#85 [CAT-259] App Icon 변경
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/themes.xml
Labels: chore

#86 [CAT-260] 휴식 대기 화면 최대 시간에 따른 navigation 추가
  app/src/main/java/com/pomonyang/mohanyang/navigation/MohaNyangNavHost.kt
  app/src/main/java/com/pomonyang/mohanyang/notification/LocalNotificationReceiver.kt
  app/src/main/java/com/pomonyang/mohanyang/ui/MohaNyangApp.kt
  app/src/main/res/values/strings.xml
  domain/src/main/java/com/pomonyang/mohanyang/domain/usecase/AdjustPomodoroTimeUseCase.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroTimerViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestWaitingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestWaitingViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingScreen.kt
Labels: feature

#83 [CAT-252] 고양이 설정 화면 Navigation 구현
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/MyPageNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/MyPageScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/MyPageViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/profile/CatProfileScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/profile/CatProfileViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/OnboardingNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/naming/OnboardingNamingCatScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/naming/OnboardingNamingCatViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatViewModel.kt
Labels: feature

#84 [CAT-256] 뽀모도르 대기화면 / Timer Text Component 수정
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/component/Timer.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestWaitingScreen.kt
  presentation/src/main/res/raw/loti_rest_waiting.json
  presentation/src/main/res/raw/loti_rest_waiting_complete_focus.json
  presentation/src/main/res/values/strings.xml
Labels: feature

#88 [CAT-262] Splash 디자인 적용
  app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
  app/src/main/res/drawable/app_splash.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/MyPageScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: feature

#89 [CAT-271] OS별 알림 권한 대응
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
  app/src/main/java/com/pomonyang/mohanyang/notification/FocusNotificationService.kt
  app/src/main/java/com/pomonyang/mohanyang/notification/MnFirebaseMessagingService.kt
  app/src/main/java/com/pomonyang/mohanyang/notification/util/NotificationUtils.kt
  app/src/main/res/drawable/ic_app_notification.xml
  data/src/main/java/com/pomonyang/mohanyang/data/repository/push/PushAlarmRepositoryImpl.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/MyPageScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/MyPageViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/util/MnNotificationManager.kt
Labels: feature

#90 [CAT-279] 온보딩 가이드 이미지 교체 및 tooltip background 수정
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/toast/MnToastSnackbarHost.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/guide/OnboardingGuideScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/model/OnboardingGuideContent.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatScreen.kt
  presentation/src/main/res/drawable/ic_app.xml
  presentation/src/main/res/drawable/onboarding_contents_1.xml
  presentation/src/main/res/drawable/onboarding_contents_2.xml
  presentation/src/main/res/drawable/onboarding_contents_3.xml
  presentation/src/main/res/values/arrays.xml
  presentation/src/main/res/values/strings.xml
Labels: chore

#91 [CAT-269] CatRive 화면별 대응
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/model/cat/CatInfoModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroTimerScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroTimerViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingViewModel.kt
  presentation/src/main/res/raw/cat_motion_transparent.riv
  presentation/src/main/res/values/strings.xml
Labels: chore

#94 [CAT-285] RIVE 적용
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/component/CatRive.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/model/cat/CatType.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/MyPageNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/profile/CatProfileScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/naming/OnboardingNamingCatScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroTimerScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingScreen.kt
  presentation/src/main/res/raw/cat_focus.riv
  presentation/src/main/res/raw/cat_home.riv
  presentation/src/main/res/raw/cat_rest.riv
  presentation/src/main/res/raw/cat_select.riv
  presentation/src/main/res/raw/cat_select_motion.riv
Labels: feature

#96 [CAT-293] Rive 깜빡임 문제 해결
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/component/CatRive.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/MyPageNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/profile/CatProfileScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/OnboardingNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/naming/OnboardingNamingCatScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatViewModel.kt
Labels: feature

#97 [CAT-297] 온보딩 RIVE 애니메이션 적용 액션 변경 / RIVE Version Upgrade
  app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
  gradle/libs.versions.toml
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/component/CatRive.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/model/cat/CatType.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/profile/CatProfileScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/naming/OnboardingNamingCatScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/PomodoroTimerScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/rest/PomodoroRestScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/setting/PomodoroSettingScreen.kt
  presentation/src/main/res/raw/cat_rename_2.riv
  presentation/src/main/res/raw/cat_select_2.riv
Labels: feature

#98 [CAT-305] 고양이 선택화면 네트워크 지연 처리
  app/src/main/java/com/pomonyang/mohanyang/navigation/MohaNyangNavHost.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/profile/CatProfileViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/OnboardingNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatViewModel.kt
Labels: feature

#99 [CAT-306] 카테고리 설정 집중 N | 집중 N 으로 나오는 버그 해결
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/button/select/MnSelectList.kt
Labels: bug
