Repository Nexters/PomoNyang-Android, pull requests merged in 2024-11, with the labels that each got.

#144 [SCRM-40] 데이터독 셋업 수정 및 트래킹 옵션 추가
  app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
  app/src/main/java/com/pomonyang/mohanyang/MohaNyangApplication.kt
  build-logic/src/main/java/com/pomonyang/mohanyang/AndroidDatadogConventionPlugin.kt
  data/build.gradle.kts
  data/src/main/java/com/pomonyang/mohanyang/data/remote/di/NetworkModule.kt
  gradle/libs.versions.toml
Labels: chore

#145 [Scrum 44] 뽀모도르 알림 UI/UX 개선
  app/src/main/java/com/pomonyang/mohanyang/di/ServiceModule.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/di/PomodoroModule.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/noti/PomodoroNotificationBitmapGenerator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/noti/PomodoroNotificationContentFactory.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/noti/PomodoroNotificationManager.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/PomodoroConstants.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/pomodoro/focus/PomodoroFocusScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/service/BasePomodoroTimer.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/service/PomodoroTimer.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/service/PomodoroTimerEventHandler.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/service/PomodoroTimerServiceExtras.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/service/focus/FocusTimer.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/service/focus/PomodoroFocusTimerService.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/service/rest/PomodoroRestTimerService.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/service/rest/RestTimer.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/util/IntentUtils.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/util/TimerUtils.kt
  presentation/src/main/res/layout/notification_pomodoro_expand.xml
  presentation/src/main/res/layout/notification_pomodoro_standard.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/strings.xml
Labels: feature

#146 [SCRUM-38] 마이페이지 디자인 QA 반영
  app/src/main/java/com/pomonyang/mohanyang/ui/MohaNyangApp.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/component/CatRive.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/textfield/MnTextField.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/MyPageElements.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/MyPageScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/MyPageViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/naming/OnboardingNamingCatScreen.kt
  presentation/src/main/res/drawable/ic_static_ready.xml
  presentation/src/main/res/values/strings.xml
Labels: feature

#149 [SCRUM-54] 잠금화면 타이머 노출 옵션 기능 구현
  data/src/main/java/com/pomonyang/mohanyang/data/local/datastore/datasource/notification/NotificationLocalDataSource.kt
  data/src/main/java/com/pomonyang/mohanyang/data/local/datastore/datasource/notification/NotificationLocalDataSourceImpl.kt
  data/src/main/java/com/pomonyang/mohanyang/data/repository/push/PushAlarmRepository.kt
  data/src/main/java/com/pomonyang/mohanyang/data/repository/push/PushAlarmRepositoryImpl.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/noti/PomodoroNotificationManager.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/MyPageElements.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/MyPageScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/MyPageViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: feature

#147 [SCRUM-39] 에러&로딩 화면 구현 및 적용
  app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
  app/src/main/java/com/pomonyang/mohanyang/MainElements.kt
  app/src/main/java/com/pomonyang/mohanyang/MainViewModel.kt
  data/src/main/java/com/pomonyang/mohanyang/data/remote/util/NetworkException.kt
  data/src/main/java/com/pomonyang/mohanyang/data/remote/util/NetworkResultCall.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/base/BaseViewElements.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/designsystem/spinner/MnSpinner.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/common/LoadingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/common/NetworkErrorDialog.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/common/NetworkErrorScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/common/ServerErrorScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/home/time/PomodoroTimeSettingElements.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/home/time/PomodoroTimeSettingScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/home/time/PomodoroTimeSettingViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/OnboardingNavigator.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/naming/OnboardingNamingCatScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/naming/OnboardingNamingCatViewModel.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/naming/OnboardingNamingElements.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatElements.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatScreen.kt
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/onboarding/select/OnboardingSelectCatViewModel.kt
  presentation/src/main/res/drawable/ic_error.xml
  presentation/src/main/res/drawable/ic_internet.xml
  presentation/src/main/res/raw/spinner.json
  presentation/src/main/res/values/strings.xml
Labels: feature

#152 [SCRUM-61] 채널 마이그레이션 오류 수정
  app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
  app/src/main/res/values/strings.xml
Labels: bug

#153 [SCRUM-62] 터치 시 말풍선 랜덤 노출 기능 구현
  presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/home/setting/PomodoroSettingScreen.kt
Labels: feature
